version: '3.1'

services:

  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: cs261
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fas200
    volumes:
        - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"